[cerebrium.deployment]
name = "imagenet-classifier"
python_version = "3.11"
docker_base_image_url = "Dockerfile"
disable_auth = false
include = [
    "app.py",
    "main.py",
    "model.py", 
    "requirements.txt",
    "imagenet_classifier.onnx",
    "Dockerfile",
    "cerebrium.toml"
]
exclude = [
    "*.pth",
    "test_*.py",
    "deploy.py",
    "convert_to_onnx.py",
    "pytorch_model.py",
    "*.pyc",
    "__pycache__",
    ".git",
    "*.md",
    "test_images",
    ".pytest_cache",
    "temp_init"
]

[cerebrium.hardware]
cpu = 2.0
memory = 4.0
compute = "CPU"

[cerebrium.scaling]
min_replicas = 0
max_replicas = 5
cooldown = 30
replica_concurrency = 1
response_grace_period = 900
scaling_metric = "concurrency_utilization"
scaling_target = 100
scaling_buffer = 0
roll_out_duration_seconds = 0 